# If you see me, please update my `rev` field using the provided links
# Click the repo and update to latest tags.
# If things break on update, raise an issue
repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.4.2
    hooks:
      - id: black
        name: black formatter ALP
        entry: black
        language: python
        exclude: '^ALP/evaluation/|^ALP/transformer_prediction_interface\.py$|^ALP/util/'

      - id: black-jupyter
        name: black-jupyter
        entry: black
        language: python
        exclude: '^ALP/evaluation/|^ALP/transformer_prediction_interface\.py$|^ALP/util/'


  - repo: local
    hooks:
      - id: ruff
        name: ruff
        language: python
        types: [ python ]
        entry: ruff check --no-cache --fix
        exclude: '^ALP/evaluation/|^ALP/transformer_prediction_interface\.py$|^ALP/util/'


  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        name: flake8 ALP
        files: ALP
        exclude: '^ALP/evaluation/|^ALP/transformer_prediction_interface\.py$|^ALP/util/'


      - id: flake8
        name: flake8 tests
        files: tests
        exclude: '^ALP/evaluation/|^ALP/transformer_prediction_interface\.py$|^ALP/util/'
