PY_EXPERIMENTER:
    n_jobs: 10
    Database:
        provider: mysql
        database: ALP_evaluation
        table:
            name: salt_setting
            keyfields:
                "setting_name":
                    type: TEXT
                    #values: [ "empty", "small", "medium", "large" ]
                "setting_labeled_train_size":
                    type: FLOAT
                    #values: [ 30, 100, 300 ]
                    # values for absolute: [30, 100, 300]
                "setting_train_type":
                    type: TEXT
                    #values: [ "absolute" ]
                "setting_test_size":
                    type: FLOAT
                    #values: [ 0.25, 0.33]
                "number_of_iterations":
                    type: INT
                    #values: [ 10, 20, 30 ]
                "number_of_samples":
                    type: INT
                    #values: [ 1, 5, 10, 20 ]
