PY_EXPERIMENTER:
  n_jobs: 1

  Database:
    provider: mysql
    database: ALPBenchmark
    table:
      name: large_setting
      keyfields:
        "setting_name":
          type: VARCHAR(50)
        "openml_id":
          type: INT
          #values: [ 3, 6, 8 ]
        "learner_name":
          type: VARCHAR(50)
          #values: [ "svm_lin", "svm_rbf", "rf_entropy" ]
        "sampling_strategy_name":
          type: VARCHAR(50)
          #values: [ "random", "entropy", "margin" ]
        "test_split_seed":
          type: INT
          #values: [ 0 ]
        "train_split_seed":
          type: INT
          #values: [ 0 ]
        "seed":
          type: INT
          #values: [ 0 ]

    logtables:
      accuracy_log:
        model_dict: TEXT

      labeling_log:
        data_dict: TEXT



